version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "java/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "nodejs/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "python/"
    schedule:
      interval: "weekly"            
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"