name: "1. Java"

on: push

jobs:
  call-workflow-ci-java-gradle:
    uses: kumabes-org/reusable-workflows-ci-java-gradle/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "java"
      shell: "bash"
      project-name: "webapp"
      java-distribution: "zulu"
      java-version: "17"
      gradle-version: "8.3"
    secrets: inherit

  Build-Docker:
    needs:
      - call-workflow-ci-java-gradle
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: java
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: "webapp"
          path: "./java/build"

      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./java/Dockerfile"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rotoku/java-webapp

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./java
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            rotoku/java-webapp:${{ github.sha }}
            rotoku/java-webapp:latest
          labels: ${{ steps.meta.outputs.labels }}
