name: "1. NodeJS"

on:
  pull_request:
    branches: ["main"]

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: nodejs
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./nodejs/Dockerfile"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rotoku/nodejs-webapp

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./nodejs
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            rotoku/nodejs-webapp:${{ github.sha }}
            rotoku/nodejs-webapp:latest
          labels: ${{ steps.meta.outputs.labels }}
