name: "secret scanning thrirdy party"

on: push

jobs:
  analyze:
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Secret Scanning Test Suite
        uses: advanced-security/secret-scanning-tools@v1
